spring.application.name=aggregator
kafka.producer.bootstrap-server=localhost:9092

kafka.producer.client.id.config=producer-2
kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value-serializer=ru.program.aggregator.avro.GeneralAvroSerializer

kafka.telemetry-sensors-topic=telemetry.sensors.v1
kafka.telemetry-snapshots-topic=telemetry.snapshots.v1

kafka.consumer.group-id=aggregator-group
kafka.consumer.client-id-config=sensor-event-consumer
kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.value-deserializer=ru.program.aggregator.avro.SensorEventDeserializer
kafka.consumer.timeout-ms=1000

kafka.config.sensor-events-topic=telemetry.sensors.v1
kafka.config.sensor-snapshots-topic=telemetry.snapshots.v1